name: Alpace API Automation CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r robot-framework_requirements.txt

      # Step 4: Pass secrets as environment variables and run the tests
      - name: Run Robot Framework tests
        run: |
          mkdir -p results
          robot --variable API_KEY:${{ secrets.API_KEY }} --variable API_SECRET:${{ secrets.SECRET_KEY }} --outputdir results Test_Suites/
          
        env:
          BASE_URL: ${{ secrets.BASE_URL }}  # Example for setting environment variable directly

      # Step 5: Archive test results
      - name: Archive test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: results/